
export const userData = [
    {
        name: "Jan",
        "Active User": 4000,
    },
    {
        name: "Feb",
        "Active User": 3000,
    },
    {
        name: "Mar",
        "Active User": 5000,
    },
    {
        name: "Apr",
        "Active User": 2000,
    },
    {
        name: "May",
        "Active User": 3000,
    },
    {
        name: "Jun",
        "Active User": 2000,
    },
    {
        name: "Jul",
        "Active User": 1000,
    },
    {
        name: "Agu",
        "Active User": 3000,
    },
    {
        name: "Sep",
        "Active User": 4000,
    },
    {
        name: "Oct",
        "Active User": 1000,
    },
    {
        name: "Nov",
        "Active User": 4000,
    },
    {
        name: "Dec",
        "Active User": 3000,
    },     
                              
      ];

      export const productData = [
        {
          name: "Jan",
          "Sales": 4000,
        },
        {
          name: "Feb",
          "Sales": 3000,
        },
        {
          name: "Mar",
          "Sales": 5000,
        },
      ];

      export const userRows = [
        { id: 1, userName: "Mine Öktem", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIW1dCeAr2FxxK-qeHScQPeueOMwmZJQIMBg&usqp=CAU",
        email:"mineoktem@gmail.com",
        status:"active",
        transaction:"$1300.00",
        },
        { id: 2, userName: "Tim Bray", 
        avatar:"https://pathrise-website-guide-wp.s3.us-west-1.amazonaws.com/guides/wp-content/uploads/2019/09/26230659/mimi-thian-5ZnS3wK6sUg-unsplash.jpeg",
        email:"timbray@gmail.com",
        status:"active",
        transaction:"$150.00",
        },
        { id: 3, userName: "Paul Buchheit", 
        avatar:"https://pathrise-website-guide-wp.s3.us-west-1.amazonaws.com/guides/wp-content/uploads/2019/03/10183927/danial-ricaros-785707-unsplash.jpeg",
        email:"paulbuchheit@gmail.com",
        status:"active",
        transaction:"$120.00",
        },
        { id: 4, userName: "John Carmack", 
        avatar:"https://resurety.com/wp-content/uploads/2022/04/Shane-Hall-400x400-1.jpg",
        email:"johncarmack@gmail.com",
        status:"active",
        transaction:"$20.00",
        },
        { id: 5, userName: "Dave Cutler", 
        avatar:"https://a.storyblok.com/f/133707/7952x5304/60e7113e1c/thisisengineering-raeng-xycbw1uip_m-unsplash.jpg/m/400x400",
        email:"davecutler@gmail.com",
        status:"active",
        transaction:"$200.00",
        },
        { id: 6, userName: "Max Levi", 
        avatar:"https://jobs.lime-technologies.com/wp-content/uploads/2019/12/Developer-2.png",
        email:"maxlevi@gmail.com",
        status:"active",
        transaction:"$350.40",
        },
        { id: 7, userName: "Pierre Omidyar", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOfUaEDw9dIiguDrOHLk1qq01i0jiAQxjRnw&usqp=CAU",
        email:"pierreomidyar@gmail.com",
        status:"active",
        transaction:"$400.00",
        },
        { id: 8, userName: "Alexey Pazhitnov", 
        avatar:"https://cdn.theorg.com/acf0cd21-d3c8-49d7-8d88-67318e19aeda_small.jpg",
        email:"alexeypazhitnov@gmail.com",
        status:"active",
        transaction:"$720.00",
        },
        { id: 9, userName: "Jimmy Wales", 
        avatar:"https://product.hubspot.com/hubfs/Mike_Axiak.jpg",
        email:"jimmywales@gmail.com",
        status:"active",
        transaction:"$1200.00",
        },
        { id: 10, userName: "Michael Widenius", 
        avatar:"https://assets.ingenuity.siemens.com/uploads/2022/09/avatar-14688-400x400.jpg",
        email:"michaelwidenius@gmail.com",
        status:"active",
        transaction:"$120.00",
        },
        { id: 11, userName: "Jamie Zawinski", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_cpUuV0VAJmQfg0R0FFYvUic2eK65uRGtEA&usqp=CAU",
        email:"jamiezawinski@gmail.com",
        status:"active",
        transaction:"$150.00",
        },
        { id: 12, userName: "Jack Dorsey", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwRpKEQ6HQF93YcX2xmmQDc6Th_4e8nLIHkg&usqp=CAU",
        email:"jackdorsey@gmail.com",
        status:"active",
        transaction:"$750.00",
        },
        { id: 13, userName: "Steve McConnell", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6zWNrEH8j3LrLpaFjbmC-8PLUidxsSpBcWQ&usqp=CAU",
        email:"stevemcconnell@gmail.com",
        status:"active",
        transaction:"$1350.00",
        },
        { id: 14, userName: "Michael Jr", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwsE0vWHGi85kFHO32aBN6TpETMv56F8UbuQ&usqp=CAU",
        email:"michaeljr@gmail.com",
        status:"active",
        transaction:"$145.00",
        },
        { id: 15, userName: "Mark Zuckerberg", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuL5NWlDljg4gW6Nc9vSdggvAJ9aFlCHB2Lg&usqp=CAU",
        email:"markz@gmail.com",
        status:"active",
        transaction:"$1000.00",
        },
        { id: 16, userName: "Bill Smith", 
        avatar:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYDaZn4OErK-kymqxVsCKE5rKfZWnRM8wlug&usqp=CAU",
        email:"billsmith@gmail.com",
        status:"active",
        transaction:"$150.00",
        },

      ];

      export const productRows = [
        {
          id: 1,
          name: "Apple Airpods",
          img:
            "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
          stock: 123,
          status: "active",
          price: "$120.00",
        },
        {
          id: 2,
          name: "iPhone",
          img:
            "https://target.scene7.com/is/image/Target/GUEST_49f3614e-c392-440f-ab24-7dd7ad5df504",
          stock: 123,
          status: "active",
          price: "$1500.00",
        },
        {
          id: 3,
          name: "Nikon",
          img:
            "http://fotografbilgimerkezi.com/wp-content/uploads/2013/02/D7100_18_105.jpg",
          stock: 123,
          status: "active",
          price: "$200.00",
        },
        {
          id: 4,
          name: "Asus Laptop",
          img:
            "https://www.artsistem.com/tr/site/show_image/upload/editor/cache/data/ckfinder/images/xml_resimleri/UN110ASU0422_53147-400x400.jpg",
          stock: 123,
          status: "active",
          price: "$3000.00",
        },
        {
          id: 5,
          name: "Keyboard",
          img:
            "https://tr.thermaltake.com/pub/media/wysiwyg/key3/productcategory/keyboards01.jpg",
          stock: 123,
          status: "active",
          price: "$200.00",
        },
        {
          id: 6,
          name: "Mouse",
          img:
            "https://www.gamegaraj.com/wp-content/uploads/GameNote-MS1026-1-400x400.png",
          stock: 123,
          status: "active",
          price: "$120.00",
        },
        {
          id: 7,
          name: "Mousepad",
          img:
            "https://digipod.com.tr/image/cache/catalog/yeni%20ithalat%20yapt%C4%B1g%C4%B1m%C4%B1z%20mousepadler/UCGEN%20RAZER/SOL%20B%C3%9CY%C3%9CK%20ARKA%20BEYAZ-400x400.png",
          stock: 123,
          status: "active",
          price: "$20.00",
        },
        {
          id: 8,
          name: "Speaker",
          img:
            "https://www.hafizakartci.com/image/cache/catalog/powerbank-speaker/speaker/escom/kimiso-3381-series-400x400.jpg",
          stock: 123,
          status: "active",
          price: "$500.00",
        },
        {
          id: 9,
          name: "Microphone",
          img:
            "https://target.scene7.com/is/image/Target/GUEST_e539c70e-116d-4b34-99c0-d259051938d1",
          stock: 123,
          status: "active",
          price: "$420.00",
        },
        {
          id: 10,
          name: "Webcam",
          img:
            "https://findicons.com/files/icons/2320/x_mac_general/400/webcam.png",
          stock: 123,
          status: "active",
          price: "$100.00",
        },
      ];